name: Deploy WebCalculator

on: workflow_dispatch

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t webcalculator:latest .

    - name: Run Container
      run: docker run -d --name webcalculator -p 8080:8080 webcalculator:latest

    - name: List Containers
      run: docker ps -a

    - name: Wait for Application
      run: sleep 3

    - name: Verify Application
      run: |
        curl -I http://localhost:8080

    - name: Check HTTP Status Code
      run: |
        STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
        echo "HTTP Status Code: $STATUS"

        if [ "$STATUS" -eq 200 ]; then
          echo "Application deployment successful"
        else
          echo "Application deployment failed"
          exit 1
        fi
